version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: hugox-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hugox_ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - hugox-network

  # Backend API
  backend:
    build: .
    container_name: hugox-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb+srv://hungnguyenm985_db_user:XrkI1t83cbwTmgsy@cluster0.vuvcksl.mongodb.net/HUGOX
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-here
      FRONTEND_URL: http://localhost:5173
      ADMIN_FRONTEND_URL: http://localhost:5173/admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - hugox-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: hugox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hugox-network

volumes:
  mongodb_data:
  redis_data:

networks:
  hugox-network:
    driver: bridge
